# Generated by Django 3.0.6 on 2022-05-24 05:05

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(blank=True, null=True, verbose_name='fecha reunion')),
                ('hour', models.TextField(blank=True, verbose_name='hora de la reunion')),
                ('business', models.TextField(blank=True, verbose_name='asunto de la reunion')),
                ('group', models.CharField(choices=[('0', 'Ventas'), ('1', 'Administracion'), ('2', 'Gerentes')], max_length=1, verbose_name='Grupo de personas')),
            ],
            options={
                'verbose_name': 'reunion',
                'verbose_name_plural': 'reuniones',
            },
        ),
    ]
