# Generated by Django 3.0.6 on 2022-05-24 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_meeting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meeting',
            new_name='Meet',
        ),
    ]
