# Generated by Django 3.0.6 on 2022-05-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de vencimiento'),
        ),
    ]
